@startuml IIDES_Enumerations
package "IIDES Enumerations" #FFF {

    enum SuffixVocab <<enumeration>> #b0d0ed {
        Jr
        Sr
        III
        IV
    }
    enum ResidencyVocab <<enumeration>> #b0d0ed {
        Naturalized
        Permanent Resident
        Resident Alien
    }
    enum GenderVocab <<enumeration>> #b0d0ed {
        Female
        Male
        Non-binary
        Other
        Unknown
    }
    enum EducationVocab <<enumeration>> #b0d0ed {
        Associates Degree
        Bachelors Degree
        Doctorate
        High School Diploma or GED
        Masters
        Professional Degree
        Some College
        Some High School
    }
    enum MaritalStatusVocab <<enumeration>> #b0d0ed {
        Single
        Married
        Divorced
        Separated
        Widowed
    }
    struct Predisposition <<enumeration>> #b0d0ed {
        predisposition_type : PredispositionTypeVocab
        predisposition_subtype : PredispositionSubtypeVocab
        observed : boolean
    }
    interface PredispositionTypeVocab<K : V> <<map>> #b0d0ed {
        1.1 : Social and Mental Health Issues
        1.2 : A History of Rule Violations
        1.3 : Suspicious Associations
        2.4 : Personal Stressful Events
    }
    interface PredispositionSubtypeVocab<K : V> <<map>> #b0d0ed {
        1.1.1 : Possible Psychological Issues
        1.1.2 : Diagnosed Psychological Issues
        1.1.3 : Gambling Problems
        1.1.4 : Substance Abuse
        1.1.5 : A History Of Financial Problems
        1.1.6 : Poor Hygiene
        1.1.7 : Risk Taker
        ..
        1.2.1 : Previous Arrest/Conviction For Related Crime
        1.2.2 : Previous Arrest/Conviction for Unrelated Crime
        1.2.3 : Previous Perpetrator of Domestic Violence
        1.2.4 : Hacking Related Activities
        1.2.5 : Previous Attempts to Disclose Through Illegitimate Means
        1.2.6 : Pending or Previous Defendant in Civil Action
        ..
        1.3.1 : Criminal Association
        1.3.2 : Internet Underground Association
        ..
        2.4.1 : Medical Problems
        2.4.2 : Relationship Problems
        2.4.3 : Emerging Financial Problems
        2.4.4 : Family Health Issues
    }
    Predisposition *-- PredispositionTypeVocab
    Predisposition *-- PredispositionSubtypeVocab
    struct ConcerningBehavior #b0d0ed {
        date : date
        behavior : ConcerningBehaviorTypeVocab
        behavior : ConcerningBehaviorSubtypeVocab
        observed : boolean
    }
    interface ConcerningBehaviorTypeVocab<K : V> <<map>> #b0d0ed {
        3.1 : Misuse of Company Resources
        3.2 : Technical Policy Abuse
        3.3 : Interpersonal Issues
        3.4 : Financial
        3.5 : Organizational Conflict
        3.6 : Suspicious Contact
        3.7 : Relocation
    }
    interface ConcerningBehaviorSubtypeVocab<K : V> <<map>> #b0d0ed {
        3.1.1 : Theft Of Physical Company Property
        3.1.2 : Insider Expressed Ownership Of Work
        3.1.3 : Repeated Security Violations - Non-Technical
        ..
        3.2.1 : Other Unauthorized Software Acquisition
        3.2.2 : Repeated Security Violations - Technical
        3.2.3 : Unauthorized Download - Remotely
        3.2.4 : Unauthorized Download - On Site
        3.2.5 : IP Policy Violation
        3.2.6 : Violation of Need to Know
        ..
        3.3.1 : Employee Extortion, Threats, or Legal Demands
        3.3.2 : Conflict With Supervisor
        3.3.3 : Conflict With Coworker(s)
        3.3.4 : Work Attendance Problems
        3.3.5 : Human Resource Policy Violations or Complaints
        3.3.6 : Disgruntled Employee
        3.3.7 : Bragging
        3.3.8 : Concurrent Crimes
        3.3.9 : Formal Complaint
        3.3.10 : Informal Complaint
        3.3.11 : Insubordination
        3.3.12 : Physical Abuse/Harassment
        3.3.13 : Sexual Harassment
        ..
        3.4.1 : Unexplained Wealth
        3.4.2 : Employee Forms New Competing Business
        3.4.3 : Financial Conflict of Interest
        ..
        3.5.1 : Planning/Contact with Competing Organization
        3.5.2 : Employee Went To Work For A Competing Organization
        3.5.3 : Employee Sought Other Employment
        3.5.4 : Group Resignation
        3.5.5 : Insider Creates Legal Entity for Illegitimate Purpose
        3.5.6 : Falsified Background Information
        ..
        3.6.1 : Suspicious Foreign Contact
        3.6.2 : Suspicious Foreign Travel
        3.6.3 : Foreign Travel - Work Related
        3.6.4 : Planning/Contact with Conspirator
        ..
        3.7.1 : Geographic Relocation
    }
    ConcerningBehavior *-- ConcerningBehaviorTypeVocab
    ConcerningBehavior *-- ConcerningBehaviorSubtypeVocab
    enum RelationshipVocab <<enumeration>> #b0d0ed {
        Acquaintance
        Colleague
        Friend
        Relative
        Significant Other/Legal partner
        Unknown
        Other
    }
    enum RecruitmentVocab <<enumeration>> #b0d0ed {
        Avoid Detection
        Greater Payoff
        Insider Resigned
        Separation of Duties
        Share the Wealth
        Unknown
    }
    enum SponsorVocab <<enumeration>> #b0d0ed {
        Organized Crime
        State Sponsor
        Foreign National
        Criminal Enterprise
        ==
        ..Used By..
        Sponsor()
    }
    struct TechControl #f9b8bd {
        control : TechControlVocab
        date : date
    }
    enum TechControlVocab <<enumeration>> #f9b8bd {
        Access to Technical System(s) Restricted
        Access to Technical System(s) Terminated
    }
    TechControl *-- TechControlVocab
    struct HRControl #f9b8bd {
        control : HRControlVocab
        date : date
    }
    enum HRControlVocab <<enumeration>> #f9b8bd {
        Insider Demoted
        Insider Suspended
        Insider Put on Paid/Unpaid Leave
        Insider Terminated
        Poor Performance Review
        Passed Over For Promotion
        Counseling
        Referred to Employee Assistance Program
        Reported to HR
        Transferred
        Verbal Reprimand
        Written Reprimand
    }
    HRControl *-- HRControlVocab
    enum InvestigatorVocab <<enumeration>> #f9b8bd {
        Incident Response Team
        Management
        Law Enforcement
        Internal Investigators
    }
    struct Investigation #f9b8bd {
        event : InvestigationVocab
        date : date
    }
    enum InvestigationVocab <<enumeration>> #f9b8bd {
        Insider's Residence/Workplace Searched
        Evidence Found
        Insider Admits to Activity in Interview
    }
    Investigation *-- InvestigationVocab

    enum AttackMethodVocab <<enumeration>> #FFBCFF {
        4.1 Unauthorized Account Access
4.1.1: Privileged Access Abuse
4.1.2: Insider Used Shared Account
4.1.3: Insider Used Dormant or Expired Account
4.1.4: Insider Used Unattended Workstation (Unsecured)
4.1.5: Insider Used Their Account After Termination/Resignation
4.1.6: Insider Used Compromised Account
4.1.7: Used Unauthorized Access Path
4.1.8: Authorized Third-Party Account
4.1.9: Coworker's Account
4.1.10: Customer's Account
4.1.11: Database Administrator Account
4.1.12: Supervisor's Account
4.1.13: System Administrator Account
4.2 Use of Malware
4.2.1: Backdoor
4.2.2: Bootkit
4.2.3: Keylogger
4.2.4: Exploit Kit
4.2.5: Ransomware
4.2.6: Remote Access Trojan
4.2.7: Resource Exploitation Software
4.2.8: Rogue Security Software
4.2.9: Rootkit
4.2.10: Screen Capture Software
4.2.11: Spyware
4.2.12: Logic Bomb
4.2.13: Wiper
4.3 Harmful Action
4.3.1: Physical Attack to Organizational Equipment
4.3.2: Bypassed Physical Security of Organizational Facilities
4.3.3: Modified Critical Data
4.3.4: Deleted Critical Data
4.3.5: Used Data in Identity Theft
4.3.6: Exploited Known Security Vulnerabilities
4.3.7: Social Engineering of Employees
4.3.8: Used/Executed Unauthorized Software
4.4 Recruitment
4.4.1: Outsider Recruits Insider
4.4.2: Insider Recruited Outside Aid
4.4.3: Insider Recruited Coworker(s)
4.4.4: Insider Recruited by Coworker(s)
4.5 Use of Attack Tool
4.5.1: Exploitation
4.5.2: Denial of Service
4.5.3: External Hardware 
4.5.4: Information Gathering
4.5.5: Network Capture
4.5.6: Credential Exploitation
4.5.7: Remote Access
4.5.8: Vulnerability Scanning
4.6 Data Exfiltration
4.6.1: Data Exfiltration - Paper
4.6.2: Data Exfiltration - Removable Media
4.6.3: Data Exfiltration - Email
4.6.4: Data Exfiltration - Cloud Storage
4.6.5: Data Exfiltration - Web-Based
4.6.6: Data Exfiltration - Verbal
4.6.7: Data Exfiltration - Mobile Device
4.6.8: Data Exfiltration - Laptop
4.6.9: Data Exfiltration - Other Technical
4.6.10: Data Exfiltration - Other Non-Technical
4.6.11: Data Exfiltration - Unspecified/Unknown
4.7 Financial Transaction
4.7.1: Attempt to Sell Organization Information/Data/IP
4.7.2: Payoffs From Insider
4.7.3: Payoffs to Insider
4.7.4: Insider Received/Transferred Fraudulent Funds
4.7.5: Insider Made Fraudulent Purchases
4.7.6: Insider Filed Fraudulent Tax Return
4.7.7: Insider Created/Used Fraudulent Asset
4.8 Concealment
4.8.1: Insider Falsified Information
4.8.2: Insider Omitted Information
4.8.3: Insider Modified/Deleted Logs/Activity
4.8.4: Insider Physically Destroyed/Hid Evidence
4.8.5: Insider Fled or Attempted to Flee
4.8.6: Insider Created/Used an Alias
4.8.7: Insider Framed another Individual
4.8.8: Insider Made False Statements/Denied Involvement
4.8.9: Concealment of Current Illicit Activity - Other Technical
4.8.10: Concealment of Current Illicit Activity - Other Non-Technical
4.9 Communication Channels
4.9.1: Company Email
4.9.2: Company Phone
4.9.3: Instant Messaging
4.9.4: Online Forum
4.9.5: Personal Email
4.9.6: Personal Phone
4.9.7: Other Type of Communication Channel
4.10 Affected Devices
4.10.1: Company Desktop
4.10.2: Company Laptop
4.10.3: Company Mobile Device
4.10.4: Database Server
4.10.5: Email Server
4.10.6: File Server
4.10.7: Personal Computer
4.10.8: Personal Mobile Device
4.10.9: Printer/Copier/Fax
4.10.10: Web Server
4.11 Reconnaissance
4.11.1: Active Scanning
4.11.2: Gather Victim Host Information
4.11.3: Gather Victim Identity Information
4.11.4: Gather Victim Network Information
4.11.5: Gather Victim Organization Information
4.11.6: Phishing for Information
4.11.7: Search Closed Sources
4.11.8: Search Open Technical Databases
4.11.9: Search Open Websites/Domains
4.11.10: Search Victim-Owned Websites
4.12 Resource Development
4.12.1: Acquire Access
4.12.2: Acquire Infrastructure
4.12.3: Compromise Accounts
4.12.4: Compromise Infrastructure
4.12.5: Develop Capabilities
4.12.6: Establish Accounts
4.12.7: Obtain Capabilities
4.12.8: Stage Capabilities
4.13 Initial Acces
4.13.1: Drive-by Compromise
4.13.2: Exploit Public Facing Application
4.13.3: External Remote Services
4.13.4: Hardware Additions
4.13.5: Phishing
4.13.6: Replication Through Removable Media
4.13.7: Supply Chain Compromise
4.13.8: Trusted Relationship
4.13.9: Valid Accounts
4.14 Execution
4.14.1: Cloud Administration Command
4.14.2: Command and Scripting Interpreter
4.14.3: Container Administration Command
4.14.4: Deploy Container
4.14.5: Exploitation for Client Execution
4.14.6: Inter-Process Communication (IPC)
4.14.7: Native Application Programming Interface (API)
4.14.8: Scheduled Task/Job
4.14.9: Serverless Execution
4.14.10: Shared Modules
4.14.11: Software Deployment Tools
4.14.12: System Services
4.14.13: User Execution
4.14.14: Windows Management Instrumentation (WMI)
4.15 Persistence
4.15.1: Account Manipulation
4.15.2: Background Intelligence Transfer Service (BITS)
4.15.3: Boot or Logon AutoStart Execution
4.15.4: Boot or Logon Initialization Scripts
4.15.5: Create or Modify System Process
4.15.6: Event Triggered Execution
4.15.7: External Remote Services
4.15.8: Hijack Execution Flow
4.15.9: Implant Internal Image
4.15.10: Modify Authentication Process
4.15.11: Office Application Startup
4.15.12: Pre-OS Boot
4.15.13: Server Software Component
4.15.14: Traffic Signaling
4.16 Privilege Escalation
4.16.1: Abuse Elevation Control Mechanism
4.16.2: Access Token Manipulation
4.16.3: Domain Policy Modification
4.16.4: Escape to Host
4.16.5: Exploitation for Privilege Escalation
4.17 Defense Evasion
4.17.1: Build Image on Host
4.17.2: Debugger Evasion
4.17.3: Deobfuscate/Decode Files
4.17.4: Direct Volume Access
4.17.5: Execution Guardrails
4.17.6: Exploitation for Defense Evasion
4.17.7: File and Directory Permissions Modification
4.17.8: Hide Artifacts
4.17.9: Impair Defenses
4.17.10: Indicator Removal
4.17.11: Indirect Command Execution
4.17.12: Masquerading
4.17.13: Modify Cloud Computer Infrastructure
4.17.14: Modify System Image
4.17.15: Network Boundary Bridging
4.17.16: Obfuscated Files or Information
4.17.17: Plist File Modification
4.17.18: Process Injection
4.17.19: Reflective Code Loading
4.17.20: Rogue Domain Controller
4.17.21: Rootkit
4.17.22: Subvert Trust Controls
4.17.23: System Binary Proxy Execution
4.17.24: System Script Proxy Execution
4.17.25: Template Injection
4.17.26: Trusted Developer Utilities Proxy Execution
4.17.27: Unused/Unsupported Cloud Regions
4.17.28: Use Alternate Authentication Material
4.17.29: Weaken Encryption
4.18 Credential Access
4.18.1: Adversary-in-the-Middle (AiTM)
4.18.2: Brute Force
4.18.3: Credentials from Password Stores
4.18.4: Exploitation for Credential Access
4.18.5: Forced Authentication
4.18.6: Forge Web Credentials
4.18.7: Input Capture
4.18.8: OS Credential Dumping
4.18.9: Steal Application Access Token
4.18.10: Steal or Forge Authentication Certificates
4.18.11: Steal or Forge Kerberos Tickets
4.18.12: Steal Web Session Cookie
4.18.13: Unsecured Credentials
4.19 Discovery
4.19.1: Account Discovery
4.19.2: Application Window Discovery
4.19.3: Browser Information Discovery
4.19.4: Cloud Infrastructure Discovery
4.19.5: Cloud Service Dashboard
4.19.6: Debugger Evasion
4.19.7: Device Driver Discovery
4.19.8: Domain Trust Discovery
4.19.9: File and Directory Discovery
4.19.10: Group Policy Discovery
4.19.11: Network Service Discovery
4.19.12: Network Share Discovery
4.19.13: Password Policy Discovery
4.19.14: Peripheral Device Discovery
4.19.15: Permission Groups Discovery
4.19.16: Process Discovery
4.19.17: Query Registry
4.19.18: Remote System Discovery
4.19.19: Software Discovery
4.19.20: System Location Discovery
4.19.21: Systen Network Configuration Discovery
4.19.22: System Network Connection Discovery
4.19.23: System Owner/User Discovery
4.19.24: System Time Discovery
4.20 Lateral Movement
4.20.1: Exploitation of Remote Services
4.20.2: Lateral Tool Transfer
4.20.3: Remote Service Session Hijacking
4.20.4: Taint Shared Content
4.21 Collection
4.21.1: Archive Collected Data
4.21.2: Audio Capture
4.21.3: Automated Collection
4.21.4: Browser Session Hijacking
4.21.5: Clipboard Data
4.21.6: Data from Local System
4.21.7: Data from Network Shared Drive
4.21.8: Data from Removable Media
4.21.9: Data Staged
4.21.10: Email Collection
4.21.11: Input Capture
4.21.12: Screen Capture
4.21.13: Video Capture
4.22 Command Control
4.22.1: Application Layer Protocol
4.22.2: Communication Through Removable Media
4.22.3: Data Encoding
4.22.4: Dynamic Resolution
4.22.5: Encrypted Channel
4.22.6: Fallback Channels
4.22.7: Ingress Tool Transfer
4.22.8: Multi-Stage Channels
4.22.9: Non-Application Layer Protocol
4.22.10: Non-Standard Port
4.22.11: Protocol Tunneling
4.22.12: Proxy
4.23 Exfiltration
4.23.1: Automated Exfiltration
4.23.2: Data Transfer Size Limits
4.23.3: Exfiltration Over C2 Channel
4.23.4: Exfiltration Over Other Network Medium
4.23.5: Transfer Data to Cloud Account
4.24 Impact
4.24.1: Account Access Removal
4.24.2: Data Destruction
4.24.3: Defacement
4.24.4: Disk Wipe
4.24.5: Endpoint Denial of Service
4.24.6: Firmware Corruption
4.24.7: Inhibit System Recovery
4.24.8: Network Denial of Service
4.24.9: Service Stop
4.24.10: System Shutdown/Reboot
    }
}
@enduml