@startuml IIDES_Enumerations
package "IIDES Enumerations" #FFF {

    enum IncidentType {
        Fraud
        Sabotage
        Theft of IP
        Misuse
    }
    enum Suffix <<enumeration>> #D4EFDF {
        Jr
        Sr
        III
        IV
    }
    enum OrgRole <<enumeration>> {
        Beneficiary
        Victim
        Trusted Business Partner
        Other
    }
    enum OrgRelationship <<enumeration>> {
        Competitor
        Vendor
        Other
        Unknown
    }
    enum OutcomeType <<enumeration>> {
        Bankruptcy
        Data Created
        Data Deleted
        Data Read
        Data Stolen
        Monetary Damages
        Monetary Losses
        Money Stolen
        No net negative
        Other
        Restituion Ordered
        Safety Impact
        Unknown
        Used in Identity Theft
    }
    enum Relationship <<enumeration>> #D4EFDF {
        Acquaintance
        Colleague
        Friend
        Relative
        Significant Other/Legal partner
        Unknown
        Other
    }
    enum SponsorType <<enumeration>> #D4EFDF {
        Organized Crime
        State Sponsor
        Foreign National
        Criminal Enterprise
    }
}
@enduml