@startuml IIDES_Enumerations
package "IIDES Enumerations" #FFF {

    enum AttackMethodVocab <<enumeration>> #FFBCFF {

4.2 Use of Malware
4.2.1: Backdoor
4.2.2: Bootkit
4.2.3: Keylogger
4.2.4: Exploit Kit
4.2.5: Ransomware
4.2.6: Remote Access Trojan
4.2.7: Resource Exploitation Software
4.2.8: Rogue Security Software
4.2.9: Rootkit
4.2.10: Screen Capture Software
4.2.11: Spyware
4.2.12: Logic Bomb
4.2.13: Wiper

4.3 Harmful Action
4.3.1: Physical Attack to Organizational Equipment
4.3.2: Bypassed Physical Security of Organizational Facilities
4.3.3: Modified Critical Data
4.3.4: Deleted Critical Data
4.3.5: Used Data in Identity Theft
4.3.6: Exploited Known Security Vulnerabilities
4.3.7: Social Engineering of Employees
4.3.8: Used/Executed Unauthorized Software

4.6 Data Exfiltration
4.6.1: Data Exfiltration - Paper
4.6.2: Data Exfiltration - Removable Media
4.6.3: Data Exfiltration - Email
4.6.4: Data Exfiltration - Cloud Storage
4.6.5: Data Exfiltration - Web-Based
4.6.6: Data Exfiltration - Verbal
4.6.7: Data Exfiltration - Mobile Device
4.6.8: Data Exfiltration - Laptop
4.6.9: Data Exfiltration - Other Technical
4.6.10: Data Exfiltration - Other Non-Technical
4.6.11: Data Exfiltration - Unspecified/Unknown

4.9 Communication Channels
4.9.1: Company Email
4.9.2: Company Phone
4.9.3: Instant Messaging
4.9.4: Online Forum
4.9.5: Personal Email
4.9.6: Personal Phone
4.9.7: Other Type of Communication Channel
    }
}
@enduml