@startuml IIDES_Core
package "IIDES Core Relationships" #FFF {

    class Insider <<Person>> #043673 {}
    class Organization #007BC0 {}
    class Incident #009647 {}
    class Job #33c2C4 {}
    class Detection #FDB515 {}
    class Response #EF3A47 {}
    class AttackTTP #A456ED {}

    Incident --|{ Insider : commits <
    Job -- Organization : employs <
    Insider -- Job : has >
    Organization }|--|{ Incident : OrgRole
    Organization }o--o{ Organization : OrgRelationship
    Insider |o--o| Organization : owns >
    Insider }|--|{ Insider
    Incident -- Detection
    Incident -- Response
    Incident --o{ AttackTTP
}
@enduml