@startuml IIDES

Class Charge #f9b8bd {
* id : charge--80e9f464-867a-4c2d-a0d5-da3303fef9f8
* title : 18 U.S.C.
+ section : 794(c)
+ nature_of_offense : Conspiracy to gather or deliver defense information to aid a foreign government.
+ count : 1
+ plea : 3
+ plea_bargain : False
+ disposition : 2
}
Class Charge #f9b8bd {
* id : charge--de9ef24e-dd8e-4c1b-b55f-7431c324e2ad
* title : 18 U.S.C
+ section : 794(a)
+ nature_of_offense : Delivery of defense information to aid a foreign government.
+ count : 1
+ plea : 3
+ plea_bargain : False
+ disposition : 2
}
Class Charge #f9b8bd {
* id : charge--b5f8ebff-7449-4919-8e83-712df4dbbd28
* title : 18 U.S.C
+ section : 794(a)
+ nature_of_offense : Attempted delivery of defense information to aid a foreign government.
+ count : 1
+ plea : 3
+ plea_bargain : False
+ disposition : 2
}
Class Charge #f9b8bd {
* id : charge--8f108155-293c-4c7b-b780-eba524e55c9c
* title : 18 U.S.C
+ section : 1001(a)(2)
+ nature_of_offense : Making material false statements.
+ count : 1
+ plea : 3
+ plea_bargain : False
+ disposition : 2
}
Class CourtCase #f9b8bd {
* id : court-case--4715b227-cee7-49b4-95a0-f418ceb31ae5
+ case_number : 1:17-cr-154
+ case_title : United States v. Mallory
+ court_country : United States of America
+ court_state : Virginia
+ court_district : Eastern District of Virginia
+ court_type : 1
+ case_type : 2
+ defendant : ['United States of America']
+ plaintiff : ['Kevin Patrick Mallory']
+ comment : 
}
Class Detection #FDB515 {
* id : detection--28ab62a7-ef29-478d-9fcd-b06bd11dfbc6
+ first_detected : date-time
+ who_detected : ['LE']
+ detected_method : ['3']
+ logs : ['EM']
+ comment : The insider willingly contacted an acquaintance who worked in the CIA to get in touch with CIA security, indicating to the acquaintance that they had been approached by Chinese intelligence agents. There were CIA and FBI agents present during the interview, and the insider was 'visibly surprised' when secure chat messages showing their espionage appeared on the screen. The FBI agents then realized that something was astray and investigated the insider thoroughly.
}
Class Impact #D4EFDF {
* id : impact--1d3ccef3-2975-4d62-84c9-d798ec888ae6
+ high : 12
+ low : 3
+ metric : 4
+ estimated : True
}
Class Incident #009647 {
* id : incident--843c85b1-6f2d-4a64-a959-d9880905114f
+ cia_effect : ['C']
+ incident_type : ['E']
+ incident_subtype : ['E2']
+ outcome : ['DS', 'DR']
+ status : C
+ summary : The insider was a former CIA officer. They were involved in a espionage case where they were convicted of providing classified U.S. Defence information to Chinese intelligence agents, which began in 2017. The insider was motivated by financial gain: the Chinese officials would exchange top secret information for money. Once the FBI became aware, they investigated the insider, and found evidence of espionage in their home. The insider was then tried and found guilty of several espionage charges, and sentenced to 20 years of federal prison.
+ brief_summary : The insider was a former CIA officer who began to communicate with Chinese intelligence agents in 2017. They began communicating, and the insider would receive money for trasmitting classified U.S. defense information to Chinese intelligence agents. The insider was later investigated and brought to court, where he was convicted of multiple counts of espionage.
}
Class Insider #043673;text:white {
* id : insider--80fea631-33e6-440b-b86d-2d49c8d7fcd2
+ incident_role : 1
+ motive : ['1']
+ substance_use_during_incident : False
+ predispositions : [['4', '4.3']]
+ concerning_behaviors : [['3.6', '3.6.1']]
+ first_name : Kevin
+ middle_name : Patrick
+ last_name : Mallory
+ alias : ['Patrick Mallory', 'Kevin P. Mallory']
+ city : Leesburg
+ state : VA
+ country : US
+ postal_code : 20175
+ country_of_citizenship : ['US']
+ nationality : ['US']
+ gender : M
+ age : 60
+ education : 5
+ marital_status : 2
+ number_of_children : 3
}
Class Job #33c2C4 {
* id : job--ca6321b3-c176-4c2a-af6f-c825c5e1a823
+ job_function : 33
+ occupation : 33.1
* title : Case Officer/Contractor
+ position_technical : False
+ access_authorization : 5
+ employment_type : FLT
+ hire_date : 1992-01-01
+ departure_date : 2012-01-01
+ tenure : 175200:00:00
}
Class Job #33c2C4 {
* id : job--79bce694-5bd1-4fb3-bcb1-258d09fca301
+ job_function : 99
+ occupation : 99.9
* title : Consultant
+ position_technical : False
+ access_authorization : 7
+ employment_type : CTR
+ hire_date : 2012-01-01
+ departure_date : 2017-07-01
+ tenure : 48192:00:00
}
Class LegalResponse #f9b8bd {
* id : legal-response--037be7c2-d741-4153-8c85-1483bc7b2e9d
+ law_enforcement_contacted : 2017-05-12
+ insider_arrested : 2017-06-22
+ insider_charged : 2017-07-27
+ insider_pleads : 2017-07-28
+ insider_judgement : 2018-06-08
+ insider_sentenced : 2019-05-17
+ insider_charges_dropped : 
+ insider_charges_dismissed : 
+ insider_settled : 
}
Class Organization #007BC0 {
* id : organization--9b495e20-ae37-4df3-920e-88338b1298b5
+ name : U.S. Central Intelligence Agency
+ city : Washington
+ state : D.C.
+ country : US
+ postal_code : 20505
+ small_business : False
+ industry_sector : 92
+ industry_subsector : 92.811
+ business : The CIA, or Central Intelligence Agency, is an independent U.S. government agency focused on foreign intelligence and national security. They collect information about other countries, analyze it, and deliver it to policymakers to help them make decisions.
+ parent_company : U.S. Intelligence Community
+ incident_role : V
}
Class Organization #007BC0 {
* id : organization--df77b634-a57b-4654-8e1e-77fd5220fe81
+ name : Chinese Intelligence Agency
+ country : CN
+ small_business : False
+ industry_sector : 92
+ industry_subsector : 92.811
+ business : The Chinese Intelligence Agency is a Chinese agency focused on foreign intelligence and national security. 
+ parent_company : Chinese National Government
+ incident_role : B
}
Class Response #EF3A47 {
* id : response--eb4d3760-213c-4f3b-81c2-b7805376c369
+ technical_controls : [['2', '2012-01-01']]
+ investigated_by : ['3']
+ investigation_events : [['1', '2017-06-22'], ['2', '2017-06-22'], ['3', '2017-05-24']]
}
Class Sentence #f9b8bd {
* id : sentence--7b9161b8-ee82-4e11-945a-31af4e284ddd
+ sentence_type : 9
+ quantity : 20
+ metric : 4
+ concurrency : False
}
Class Source #D4EFDF {
* id : source--370b7bf9-46a4-44f4-8229-dce1c0824b62
* title : Former C.I.A. Officer Sentenced to 20 Years After Spying for China
+ source_type : 5
+ file_type : html
+ date : 2019-05-17
+ public : True
+ document : https://www.nytimes.com/2019/05/17/us/politics/cia-spying-china.html
}
Class Source #D4EFDF {
* id : source--43dfd29e-60c0-4aaa-933f-a96c2845887e
* title : US v. Kevin Mallory, No. 19-4385 (4th Cir. 2022)
+ source_type : 1
+ file_type : pdf
+ date : 2022-07-11
+ public : True
+ document : https://law.justia.com/cases/federal/appellate-courts/ca4/19-4385/19-4385-2022-07-11.html#:~:text=Kevin%20Mallory%2C%20No.-,19%2D4385%20(4th%20Cir.,2022)&text=A%20jury%20convicted%20Defendant%20of,in%20violation%20of%2018%20U.S.C.
}
Class Source #D4EFDF {
* id : source--0ae6419b-66e3-4d9f-bcb6-531cc8a4e53a
* title : United States of America v. Kevin Patrick Mallory
+ source_type : 1
+ file_type : pdf
+ date : 2017-06-21
+ public : True
+ document : https://www.justice.gov/opa/press-release/file/975671/dl
}
Class Source #D4EFDF {
* id : source--ada0e3cc-5048-4509-ad62-c06c7d34594f
* title : United States v. Mallory (2020)
+ source_type : 1
+ file_type : html
+ date : 2020-10-05
+ public : True
+ document : https://caselaw.findlaw.com/court/us-dis-crt-e-d-vir-ale-div/2173526.html
}
Class Source #D4EFDF {
* id : source--9fe4a90d-abf1-4db6-a4e1-a30e37b3ffe6
* title : United States v. Mallory (2022)
+ source_type : 1
+ file_type : html
+ date : 2022-07-11
+ public : True
+ document : https://caselaw.findlaw.com/court/us-4th-circuit/2178971.html
}
Class Source #D4EFDF {
* id : source--265815a9-494f-4034-b2cf-2d28e01b1318
* title : United States v. Mallory, Criminal No. 1:17-CR-154
+ source_type : 1
+ file_type : html
+ date : 2018-10-15
+ public : True
+ document : https://case-law.vlex.com/vid/united-states-v-mallory-888386269
}
Class Stressor #b0d0ed {
* id : stressor--40650474-f431-4ddb-9e3a-417bab254ac1
+ date : 2017-02-01
+ category : 3
+ subcategory : 3.1
+ comment : Insider was behind 2 mortgage payments and had debt they wished to pay.
}
Class Sponsor #b0d0ed {
* id : sponsor--0378da70-22a9-4998-ab9f-3fdd9f690247
+ name : Chinese Intelligence Agency
+ sponsor_type : FN
}
Class Target #D4EFDF {
* id : target--54d887da-7f59-47e1-ad5a-d611f78030da
+ asset_type : 2
+ category : 2.3
+ subcategory : 2.3.1
+ format : 1
+ owner : O
+ sensitivity : ['6']
}
Class TTP #A456ED {
* id : ttp--c130b8ca-6d8f-4696-a835-4d35448e8607
+ date : 2017-02-21
+ sequence_num : 2
+ observed : False
+ number_of_times : 7
+ ttp_vocab : IIDES
+ tactic : 7
+ technique : 1.6
+ location : remote
+ hours : 2
+ device : ['8']
+ channel : ['6']
+ description : The insider communicated repeatedly with Chinese Intelligence officers to exchange top secret information for money.
}
Class TTP #A456ED {
* id : ttp--def6dff4-cbf6-4cc5-adf6-a6880c9dc1c2
+ date : 2017-02-01
+ sequence_num : 1
+ observed : False
+ number_of_times : 1
+ ttp_vocab : IIDES
+ tactic : 2
+ technique : 2.1
+ location : remote
+ hours : 2
+ device : ['7']
+ channel : ['4']
+ description : The insider was initially recruited by a Chinese Intelligence Agent reaching out on LinkedIn asking to meet in China.
}
Class TTP #A456ED {
* id : ttp--820373f2-e55f-45bf-9a75-6a6b5e38cc3c
+ date : 2017-03-01
+ sequence_num : 1
+ observed : False
+ number_of_times : 1
+ ttp_vocab : IIDES
+ tactic : 2
+ technique : 2.1
+ location : remote
+ hours : 2
+ device : ['7']
+ channel : ['4']
+ description : The insider was initially recruited by a Chinese Intelligence Agent reaching out on LinkedIn asking to meet in China.
}


    Insider --o{ Accomplice
    Incident --|{ Insider : commits <
    Accomplice |o--o{ Job
    Job }o--o| Organization : employs <
    Insider |o--o{ Job
    Organization }o--o| Incident
    Organization }o-- OrgRelationship
    OrgRelationship --o{ Organization
    Insider }o--o| Sponsor
    Accomplice }o--o| Sponsor
    Insider }o..o{ Organization : OrgOwner >
    Accomplice }o..o{ Organization : OrgOwner >
    Insider -- Collusion
    Collusion -- Insider
    Incident --o{ Impact
    Incident --o{ Target
    Incident --o{ Source
    Incident --o{ Note
    CourtCase ||--o{ Charge
    CourtCase ||--o{ Sentence
    Incident --o| Detection
    Incident --o| Response
    Response ||--o| LegalResponse
    LegalResponse ||--o{ CourtCase
    Organization --o{ Stressor
    Stressor }o-- Insider
    Incident --o{ TTP
@enduml